import type { Template } from '@/types'

export const TEMPLATES_SEED: Template[] = [
  {
    id: 't1',
    title: 'SOC 2 Type II Evidence Collection Tracker',
    description: 'A comprehensive Excel workbook for tracking evidence collection across all TSC criteria. Includes status columns, due dates, owner assignments, and auditor notes. Fully sanitized — no client data.',
    category: 'Evidence',
    file_url: '#',
    file_format: 'xlsx',
    author_id: '1',
    author: { id: '1', username: 'SilentAuditor34', job_title: 'Senior IT Auditor', industry: 'Financial Services / Banking', experience: '6–10 years', certifications: ['CISA'], avatar_gradient: '135deg, #7b61ff, #00d4ff', is_anonymous: true, reputation: 3420, created_at: '2025-01-01T00:00:00Z' },
    download_count: 312,
    rating_avg: 4.8,
    rating_count: 47,
    tags: ['SOC 2', 'evidence', 'tracking'],
    created_at: new Date(Date.now() - 30*24*3600*1000).toISOString(),
  },
  {
    id: 't2',
    title: 'ISO 27001 Internal Audit Checklist — Annex A Controls',
    description: 'Complete checklist covering all 93 controls in ISO 27001:2022 Annex A. Each control includes the clause reference, audit question, evidence required, and a pass/fail/N-A field. Word format for easy customization.',
    category: 'Checklists',
    file_url: '#',
    file_format: 'docx',
    author_id: '4',
    author: { id: '4', username: 'MethodicalInspector7', job_title: 'IT Audit Manager', industry: 'Government / Public Sector', experience: '11–15 years', certifications: ['CISM', 'CRISC'], avatar_gradient: '135deg, #a78bfa, #7b61ff', is_anonymous: true, reputation: 1890, created_at: '2025-01-02T00:00:00Z' },
    download_count: 589,
    rating_avg: 4.9,
    rating_count: 83,
    tags: ['ISO 27001', 'checklist', 'Annex A'],
    created_at: new Date(Date.now() - 45*24*3600*1000).toISOString(),
  },
  {
    id: 't3',
    title: 'PCI DSS v4.0 SAQ-A Scoping Worksheet',
    description: 'Helps e-commerce merchants determine whether they qualify for SAQ-A and document their scoping rationale. Includes a decision tree, cardholder data flow diagram template, and scope boundary documentation.',
    category: 'Risk Assessment',
    file_url: '#',
    file_format: 'xlsx',
    author_id: '3',
    author: { id: '3', username: 'CovertAssessor11', job_title: 'QSA', industry: 'Retail / E-commerce', experience: '6–10 years', certifications: ['QSA', 'CISSP'], avatar_gradient: '135deg, #f97316, #ef4444', is_anonymous: true, reputation: 2100, created_at: '2025-01-03T00:00:00Z' },
    download_count: 201,
    rating_avg: 4.6,
    rating_count: 29,
    tags: ['PCIDSS', 'scoping', 'SAQ'],
    created_at: new Date(Date.now() - 20*24*3600*1000).toISOString(),
  },
  {
    id: 't4',
    title: 'NIST CSF 2.0 Gap Assessment Template',
    description: 'Excel-based gap assessment across all six NIST CSF 2.0 functions: Govern, Identify, Protect, Detect, Respond, Recover. Includes maturity scoring (Tier 1–4), current vs target state, and remediation priority fields.',
    category: 'Risk Assessment',
    file_url: '#',
    file_format: 'xlsx',
    author_id: '2',
    author: { id: '2', username: 'PhantomReviewer19', job_title: 'GRC Analyst', industry: 'Technology / SaaS', experience: '3–5 years', certifications: ['CISM'], avatar_gradient: '135deg, #00e5a0, #0891b2', is_anonymous: true, reputation: 2310, created_at: '2025-01-04T00:00:00Z' },
    download_count: 445,
    rating_avg: 4.7,
    rating_count: 61,
    tags: ['NIST', 'gap assessment', 'maturity'],
    created_at: new Date(Date.now() - 15*24*3600*1000).toISOString(),
  },
  {
    id: 't5',
    title: 'Access Review Attestation Letter Template',
    description: 'A one-page Word template for quarterly access review attestations. Includes fields for review period, systems reviewed, exceptions identified, remediation actions, and reviewer signature. Accepted by Big 4 auditors.',
    category: 'Evidence',
    file_url: '#',
    file_format: 'docx',
    author_id: '1',
    author: { id: '1', username: 'SilentAuditor34', job_title: 'Senior IT Auditor', industry: 'Financial Services / Banking', experience: '6–10 years', certifications: ['CISA'], avatar_gradient: '135deg, #7b61ff, #00d4ff', is_anonymous: true, reputation: 3420, created_at: '2025-01-01T00:00:00Z' },
    download_count: 178,
    rating_avg: 4.5,
    rating_count: 22,
    tags: ['access-control', 'evidence', 'SOC 2', 'ISO 27001'],
    created_at: new Date(Date.now() - 10*24*3600*1000).toISOString(),
  },
  {
    id: 't6',
    title: 'IT Audit Report Template — Executive Summary + Findings',
    description: 'Professional Word report template with executive summary, scope and methodology, findings table (risk rated High/Medium/Low), management responses section, and appendix structure. Used across SOC 2, ISO, and internal audit engagements.',
    category: 'Reports',
    file_url: '#',
    file_format: 'docx',
    author_id: '4',
    author: { id: '4', username: 'MethodicalInspector7', job_title: 'IT Audit Manager', industry: 'Government / Public Sector', experience: '11–15 years', certifications: ['CISM', 'CRISC'], avatar_gradient: '135deg, #a78bfa, #7b61ff', is_anonymous: true, reputation: 1890, created_at: '2025-01-02T00:00:00Z' },
    download_count: 634,
    rating_avg: 4.9,
    rating_count: 91,
    tags: ['reports', 'findings', 'risk'],
    created_at: new Date(Date.now() - 60*24*3600*1000).toISOString(),
  },
  {
    id: 't7',
    title: 'Vendor Risk Assessment Questionnaire — Security Controls',
    description: 'A 45-question vendor security questionnaire covering data handling, access controls, encryption, incident response, and business continuity. Includes a scoring rubric for risk tiering vendors as Critical/High/Medium/Low.',
    category: 'Risk Assessment',
    file_url: '#',
    file_format: 'xlsx',
    author_id: '2',
    author: { id: '2', username: 'PhantomReviewer19', job_title: 'GRC Analyst', industry: 'Technology / SaaS', experience: '3–5 years', certifications: ['CISM'], avatar_gradient: '135deg, #00e5a0, #0891b2', is_anonymous: true, reputation: 2310, created_at: '2025-01-04T00:00:00Z' },
    download_count: 267,
    rating_avg: 4.4,
    rating_count: 38,
    tags: ['risk', 'vendor', 'third-party'],
    created_at: new Date(Date.now() - 25*24*3600*1000).toISOString(),
  },
  {
    id: 't8',
    title: 'Acceptable Use Policy — IT Systems (Editable Template)',
    description: 'A complete Acceptable Use Policy covering email, internet, mobile devices, cloud services, and social media. Aligned with ISO 27001 A.6.2 and NIST SP 800-53. Includes employee acknowledgment signature page.',
    category: 'Policies',
    file_url: '#',
    file_format: 'docx',
    author_id: '3',
    author: { id: '3', username: 'CovertAssessor11', job_title: 'QSA', industry: 'Retail / E-commerce', experience: '6–10 years', certifications: ['QSA', 'CISSP'], avatar_gradient: '135deg, #f97316, #ef4444', is_anonymous: true, reputation: 2100, created_at: '2025-01-03T00:00:00Z' },
    download_count: 521,
    rating_avg: 4.6,
    rating_count: 72,
    tags: ['policies', 'ISO 27001', 'NIST'],
    created_at: new Date(Date.now() - 50*24*3600*1000).toISOString(),
  },
  {
    id: 't9',
    title: 'Change Management Log & Approval Tracker',
    description: 'Excel workbook for tracking IT change requests through the full lifecycle: request, risk assessment, CAB approval, implementation, and post-implementation review. Satisfies SOC 2 CC8.1 and ISO 27001 A.12.1.2 evidence requirements.',
    category: 'Evidence',
    file_url: '#',
    file_format: 'xlsx',
    author_id: '1',
    author: { id: '1', username: 'SilentAuditor34', job_title: 'Senior IT Auditor', industry: 'Financial Services / Banking', experience: '6–10 years', certifications: ['CISA'], avatar_gradient: '135deg, #7b61ff, #00d4ff', is_anonymous: true, reputation: 3420, created_at: '2025-01-01T00:00:00Z' },
    download_count: 389,
    rating_avg: 4.7,
    rating_count: 54,
    tags: ['SOC 2', 'ISO 27001', 'change management', 'evidence'],
    created_at: new Date(Date.now() - 35*24*3600*1000).toISOString(),
  },
  {
    id: 't10',
    title: 'CMMC Level 2 Practice Assessment Workbook',
    description: 'Covers all 110 practices across the 14 CMMC Level 2 domains. Each practice includes the NIST SP 800-171 mapping, assessment objective, evidence examples, and implementation status tracking. Designed for DoD contractors.',
    category: 'Checklists',
    file_url: '#',
    file_format: 'xlsx',
    author_id: '4',
    author: { id: '4', username: 'MethodicalInspector7', job_title: 'IT Audit Manager', industry: 'Government / Public Sector', experience: '11–15 years', certifications: ['CISM', 'CRISC'], avatar_gradient: '135deg, #a78bfa, #7b61ff', is_anonymous: true, reputation: 1890, created_at: '2025-01-02T00:00:00Z' },
    download_count: 143,
    rating_avg: 4.8,
    rating_count: 19,
    tags: ['CMMC', 'NIST', 'DoD', 'checklist'],
    created_at: new Date(Date.now() - 8*24*3600*1000).toISOString(),
  },
]
