import type { Question } from '@/types'

export const QUESTIONS_SEED: Question[] = [
  {
    id: '1', vote_count: 34, answer_count: 8, view_count: 412, is_answered: true, user_vote: 0,
    title: 'How should we document evidence for SOC 2 Type II user access reviews when using an automated provisioning tool?',
    body: 'We recently migrated to an automated IGA solution. Our auditors are asking for evidence of quarterly access reviews but the tool only exports machine-readable JSON logs, not the traditional Excel exports they are used to seeing...',
    tags: ['SOC 2', 'access-control', 'evidence', 'IAM'], author_id: '1',
    author: { id: '1', username: 'SilentAuditor34', job_title: 'Senior IT Auditor', industry: 'Financial Services / Banking', experience: '6–10 years', certifications: ['CISA'], avatar_gradient: '135deg, #7b61ff, #00d4ff', is_anonymous: true, reputation: 3420, created_at: '2025-01-01T00:00:00Z' },
    created_at: new Date(Date.now() - 2*3600*1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '2', vote_count: 19, answer_count: 3, view_count: 187, is_answered: false, user_vote: 0,
    title: 'Is network segmentation documentation required for NIST CSF 2.0 Protect function, or is it implied by asset inventory?',
    body: 'Clause PR.AC-5 in NIST CSF 2.0 is ambiguous on whether network diagrams count as separate evidence artifacts or can be treated as supplementary to asset inventory documentation...',
    tags: ['NIST', 'cloud', 'risk'], author_id: '2',
    author: { id: '2', username: 'PhantomReviewer19', job_title: 'GRC Analyst', industry: 'Technology / SaaS', experience: '3–5 years', certifications: ['CISM'], avatar_gradient: '135deg, #00e5a0, #0891b2', is_anonymous: true, reputation: 2310, created_at: '2025-01-02T00:00:00Z' },
    created_at: new Date(Date.now() - 5*3600*1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '3', vote_count: 11, answer_count: 1, view_count: 94, is_answered: false, user_vote: 0,
    title: 'When scoping a PCI DSS v4.0 assessment, how do we handle cloud-hosted microservices that briefly process card data in memory?',
    body: 'We have a payment gateway with ephemeral containerized services on Kubernetes. Each container processes tokenized data for milliseconds before passing it upstream. Assessor is unclear whether each pod is in-scope...',
    tags: ['PCIDSS', 'cloud', 'penetration'], author_id: '3',
    author: { id: '3', username: 'CovertAssessor11', job_title: 'QSA', industry: 'Retail / E-commerce', experience: '6–10 years', certifications: ['QSA', 'CISSP'], avatar_gradient: '135deg, #f97316, #ef4444', is_anonymous: true, reputation: 2100, created_at: '2025-01-03T00:00:00Z' },
    created_at: new Date(Date.now() - 8*3600*1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '4', vote_count: 28, answer_count: 12, view_count: 831, is_answered: true, user_vote: 0,
    title: 'Best practices for SIEM log retention periods — ISO 27001 A.12.4.1 says "as required" but what does that actually mean?',
    body: 'Clause A.12.4.1 is frustratingly vague. We are trying to set a defensible retention policy. Some regulators want 12 months hot, some 7 years archive. How have others balanced storage cost vs compliance requirements...',
    tags: ['ISO 27001', 'SIEM', 'logging'], author_id: '1',
    author: { id: '1', username: 'SilentAuditor34', job_title: 'Senior IT Auditor', industry: 'Financial Services / Banking', experience: '6–10 years', certifications: ['CISA'], avatar_gradient: '135deg, #7b61ff, #00d4ff', is_anonymous: true, reputation: 3420, created_at: '2025-01-01T00:00:00Z' },
    created_at: new Date(Date.now() - 24*3600*1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '5', vote_count: 7, answer_count: 0, view_count: 56, is_answered: false, user_vote: 0,
    title: 'Zero trust architecture audit — how do you evaluate policy engine effectiveness without access to production traffic data?',
    body: 'Client has deployed a zero trust model with a ZTNA broker but restricts auditor access to live traffic for privacy reasons. Looking for approaches to validate policy enforcement through sampling or synthetic tests...',
    tags: ['zero-trust', 'access-control', 'risk'], author_id: '4',
    author: { id: '4', username: 'MethodicalInspector7', job_title: 'IT Audit Manager', industry: 'Government / Public Sector', experience: '11–15 years', certifications: ['CISM', 'CRISC'], avatar_gradient: '135deg, #a78bfa, #7b61ff', is_anonymous: true, reputation: 1890, created_at: '2025-01-04T00:00:00Z' },
    created_at: new Date(Date.now() - 48*3600*1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '6', vote_count: 41, answer_count: 15, view_count: 1240, is_answered: true, user_vote: 0,
    title: 'How do you handle an auditee who refuses to provide evidence, claiming it is too sensitive to share?',
    body: 'We are mid-engagement on an ISO 27001 assessment and the client IT team is stonewalling requests for firewall config exports and change management logs. Engagement letter is signed. What are our options...',
    tags: ['ISO 27001', 'evidence', 'risk'], author_id: '1',
    author: { id: '1', username: 'SilentAuditor34', job_title: 'Senior IT Auditor', industry: 'Financial Services / Banking', experience: '6–10 years', certifications: ['CISA'], avatar_gradient: '135deg, #7b61ff, #00d4ff', is_anonymous: true, reputation: 3420, created_at: '2025-01-01T00:00:00Z' },
    created_at: new Date(Date.now() - 72*3600*1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '7', vote_count: 52, answer_count: 9, view_count: 2100, is_answered: true, user_vote: 0,
    title: 'MFA fatigue attack — does logging the rejected pushes alone satisfy ISO 27001 A.9.4 or do we need detective controls too?',
    body: 'Following a recent pen test finding, we confirmed our SSO logs capture rejected MFA pushes but have no automated alerting on high volumes. ISO A.9.4 is about access restrictions, but what about the detective side...',
    tags: ['ISO 27001', 'IAM', 'logging', 'risk'], author_id: '2',
    author: { id: '2', username: 'PhantomReviewer19', job_title: 'GRC Analyst', industry: 'Technology / SaaS', experience: '3–5 years', certifications: ['CISM'], avatar_gradient: '135deg, #00e5a0, #0891b2', is_anonymous: true, reputation: 2310, created_at: '2025-01-02T00:00:00Z' },
    created_at: new Date(Date.now() - 96*3600*1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '8', vote_count: 3, answer_count: 0, view_count: 21, is_answered: false, user_vote: 0,
    title: 'Is a read-only service account with no login shell still in scope for privileged access review under NIST SP 800-53?',
    body: 'We have dozens of read-only service accounts used for monitoring pipelines. They have no interactive login capability. Our new auditor is flagging them as privileged accounts requiring quarterly review...',
    tags: ['NIST', 'access-control', 'IAM'], author_id: '5',
    author: { id: '5', username: 'TacticalValidator3', job_title: 'Cybersecurity Auditor', industry: 'Technology / SaaS', experience: '0–2 years', certifications: [], avatar_gradient: '135deg, #00d4ff, #0891b2', is_anonymous: true, reputation: 412, created_at: '2025-01-05T00:00:00Z' },
    created_at: new Date(Date.now() - 1*3600*1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '9', vote_count: 0, answer_count: 0, view_count: 8, is_answered: false, user_vote: 0,
    title: 'GDPR Article 32 vs ISO 27001 — can the same risk assessment satisfy both frameworks simultaneously?',
    body: 'We are trying to avoid running two parallel risk assessment processes for a client who needs both ISO 27001 certification and GDPR compliance. Looking for a mapping or unified approach that auditors will accept...',
    tags: ['GDPR', 'ISO 27001', 'risk'], author_id: '2',
    author: { id: '2', username: 'PhantomReviewer19', job_title: 'GRC Analyst', industry: 'Technology / SaaS', experience: '3–5 years', certifications: ['CISM'], avatar_gradient: '135deg, #00e5a0, #0891b2', is_anonymous: true, reputation: 2310, created_at: '2025-01-02T00:00:00Z' },
    created_at: new Date(Date.now() - 0.5*3600*1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '10', vote_count: 22, answer_count: 6, view_count: 503, is_answered: true, user_vote: 0,
    title: 'Cloud-shared responsibility matrix — who owns OS-level patching evidence for PaaS workloads in SOC 2 Type II?',
    body: 'Our client runs containerized workloads on Google Cloud Run. We need to address CC7.1 (system operations) and CC6.8 (malicious code) but the OS layer is fully managed by GCP. How have others handled evidence...',
    tags: ['SOC 2', 'cloud', 'evidence'], author_id: '3',
    author: { id: '3', username: 'CovertAssessor11', job_title: 'QSA', industry: 'Retail / E-commerce', experience: '6–10 years', certifications: ['QSA', 'CISSP'], avatar_gradient: '135deg, #f97316, #ef4444', is_anonymous: true, reputation: 2100, created_at: '2025-01-03T00:00:00Z' },
    created_at: new Date(Date.now() - 36*3600*1000).toISOString(), updated_at: new Date().toISOString(),
  },
]
